bbs/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from web import views
from web_chat import urls as chat_urls
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bbs.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^chat/', include(chat_urls)),
    url(r'^category/(\d+)/$', views.category,name='category'),
    url(r'^article/(\d+)/$', views.article_detail,name='article_detail'),
    url(r'^account/logout/', views.acc_logout,name='logout'),
    url(r'^account/login/', views.acc_login,name='login'),
    url(r'^article/new/', views.new_article,name='new_article'),


    url(r'^$', views.index,name='index'),
)

web/models.py
#coding:utf-8

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    '''
    帖子表
    '''
    title = models.CharField(u"文章标题",max_length=255,unique=True)
    categroy = models.ForeignKey("Category",verbose_name=u"板块")
    head_img = models.ImageField(upload_to="uploads")
    summary = models.CharField(max_length=255)
    content = models.TextField(u"内容")
    author = models.ForeignKey("UserProfile")
    publish_date = models.DateTimeField(auto_now=True)
    hidden = models.BooleanField(default=True)
    priority = models.IntegerField(u"优先级",default=1000)

    def __unicode__(self):
        return "<%s, author:%s>" %(self.title,self.author)

class Comment(models.Model):
    '''
    存储所有的评论
    '''
    article = models.ForeignKey(Article)
    user = models.ForeignKey("UserProfile")
    #parent_comment = models.ForeignKey('Comment',)
    parent_comment = models.ForeignKey('self',related_name='p_comment',blank=True,null=True)
    comment = models.TextField(max_length=1000)
    date = models.DateTimeField(auto_now=True)
    def __unicode__(self):
        return "<%s, user:%s>" %(self.comment,self.user)

class ThumbUp(models.Model):
    '''点赞'''
    article = models.ForeignKey('Article')
    user = models.ForeignKey('UserProfile')
    date = models.DateTimeField(auto_now=True)
    def __unicode__(self):
        return "<user:%s>" %(self.user)

class Category(models.Model):
    '''
    帖子版块
    '''
    name = models.CharField(max_length=64,unique=True)
    admin = models.ManyToManyField('UserProfile')
    def __unicode__(self):
        return self.name

class UserProfile(models.Model):
    '''
    账户信息表
    '''
    user = models.OneToOneField(User)
    name = models.CharField(max_length=32)
    groups = models.ManyToManyField('UserGroup')
    friends = models.ManyToManyField('self',related_name='my_friends')
    def __unicode__(self):
        return self.name



class UserGroup(models.Model):
    '''
    用户组
    '''
    name = models.CharField(max_length=64,unique=True)

    def __unicode__(self):
        return self.name

templates/article.html
{% extends 'index.html' %}
{% block encodqution %}
<!-- saved from url=(0054)http://v3.bootcss.com/examples/navbar-fixed-top/#about -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">
{% endblock %}


{% load comment_tags %}


{% block content %}
{#    <div class="row">#}
{#    <div >#}
        <div class="article_detail">
            <br>

            <h4 style="">{{ article_obj.title }}</h4>

            <br>

            <p>{{ article_obj.content | safe }}</p>
            <hr/>
            <span>评论: </span>
            <br>
            {% comment_tree_tag article_obj.comment_set.select_related %}

        <br>
        </div>
{#    </div>#}

{% endblock %}

templates/index.html
{% block encodqution %}
<!DOCTYPE html>
<!-- saved from url=(0054)http://v3.bootcss.com/examples/navbar-fixed-top/#about -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">
{% endblock %}

    <title>果子社区</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/bootstrap/css/navbar-fixed-top.css" rel="stylesheet">
    <link href="/static/bootstrap/css/custom.css" rel="stylesheet">

    {% block head-js %}
    {% endblock %}
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top" >
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://v3.bootcss.com/examples/navbar-fixed-top/#">果子新闻社区</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li ><a href="{% url 'index' %}">全部</a></li>
            <li><a href="{% url 'category' 1 %}">国内</a></li>
            <li><a href="{% url 'category' 2 %}">广东</a></li>
            <li><a href="{% url 'category' 3 %}">国际</a></li>
            <li><a href="{% url 'category' 4 %}">趣闻</a></li>
            <li><a href="{% url 'web_chat' %}">聊天区</a></li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
              {% if request.user.is_authenticated %}
                <li class="dropdown">
              <a href="http://v3.bootcss.com/examples/navbar-fixed-top/#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">{{ request.user.userprofile.name }} <span class="caret"></span></a>
{#                   方向关系， 因为是一对一原生表user，所以只需.什么的就可以，而如果是一对多就要_set取#}
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'new_article' %}">发帖</a></li>
                <li><a href="http://v3.bootcss.com/examples/navbar-fixed-top/#">Action</a></li>
                <li><a href="http://v3.bootcss.com/examples/navbar-fixed-top/#">Another action</a></li>
                <li><a href="http://v3.bootcss.com/examples/navbar-fixed-top/#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="http://v3.bootcss.com/examples/navbar-fixed-top/#">Separated link</a></li>
                <li><a href="{% url 'logout' %}">退出</a></li>
              </ul>
            </li>
              {% else %}
                   <li><a href="{% url 'login' %}">注册\登陆</a></li>
              {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

        {% block content %}
            <div class="row">
                <div class="col-md-8 left-content-panel">
                    <div class="content-box">
                        {% for article in articles reversed %}
                            <br>
                                <div class="article-box row">
                                    <div class="article-head-img col-md-3">
                                        <img src="{{ article.head_img }}">
                                    </div>
                                    <div class="article-summary col-md-8">
                                        <h4 ><a href="{% url 'article_detail' article.id %}">{{ article.title }}</a></h4>
                                        <div class="article-attr">
                                            <ul class="list-inline">
                                                <li>作者:{{ article.author.name }}</li>
                                                <li>时间:{{ article.publish_date|date:"Y-m-d H:i:s" }}</li>
                                                <li>点赞:{{ article.thumbup_set.select_related.count }}</li>
                                                <li>评论:{{ article.comment_set.select_related.count }}</li>
                                            </ul>
                                        </div>
                                        <p>
                                            {{ article.summary }}
                                        </p>
                                    </div>

                                </div>
                            <hr>
                        {% endfor %}


                    </div>
                </div>
{#                   聊天区#}
                    <div class="col-md-4 right-sidebar">
                        <h3>聊天区</h3>
                    </div>
            </div>
        {% endblock %}
{#             <div class="col-md-4 right-sidebar">#}
{#            ssdggghh#}
{#            </div>#}



    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/bootstrap/js/jquery-2.1.4.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/bootstrap/js/ie10-viewport-bug-workaround.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){

            var menus = $("#navbar a[href='{{ request.path }}']")[0];

            $(menus).parent().addClass("active");
            $(menus).parent().siblings().removeClass("active");
            //console.log(menus);
        });


    </script>

        {% block bottom-js %}
        {% endblock %}
  

</body></html>

templates/login.html
{% extends 'index.html' %}

{% block content %}
    <div class="col-md-5 left-content-panel">
        <form class="form-signin" action="{% url 'login' %}" method="post">{% csrf_token %}
            <h2 class="form-signin-heading">Please sign in</h2>
            <input type="text" name="username" class="form-control" placeholder="username" required="" autofocus="">
            <br>
            <input type="password" name="password" class="form-control" placeholder="Password" required="">
            <div class="checkbox">
              <label>
                <input type="checkbox" value="remember-me"> Remember me
              </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button><br>
            <p style="color: red">{{ err_msg }}</p>
        </form>
    </div>

      <div class="col-md-5 left-content-panel">
        <form class="form-signin" action="{% url 'login' %}" method="post">{% csrf_token %}
            <h2 class="form-signin-heading">regite your user</h2>
            <input type="text" name="username" class="form-control" placeholder="username" required="" autofocus="">
            <br>
            <input type="password" name="password" class="form-control" placeholder="Password" required="">
            <div class="checkbox">
              <label>
                <input type="checkbox" value="remember-me"> Remember me
              </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button><br>
            <p style="color: red">{{ err_msg }}</p>
        </form>
    </div>


{% endblock %}

templates/new_article.html
{% extends 'index.html' %}

{% block head-js %}
    <script src="/static/plugins/ckeditor/ckeditor.js"></script>
{% endblock %}

{% block content %}
{#   <div class="col-md-5 left-content-panel">#}
    <div class="new-article">
    {% if new_article_obj %}
        <h3>文章<{{ new_article_obj.title }}>已发布，<a href="{% url 'article_detail' new_article_obj.id %}">点我查看</a></h3>
    {% else %}
          <br>
           <br>

           <div>
            <form action="{% url 'new_article' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
                <input name="title" type="text" class="form-control" placeholder="文章标题"/>
            <br>

                <span>板块:</span>

                <select name="categroy_id" class="form-control">
                {% for catrgory in category_list %}
                        <option value="{{ catrgory.id }}">{{ catrgory.name }}</option>
                {% endfor %}

                </select>
            <br>

                <input name="summary" type="text" class="form-control" placeholder="一句话概括文章" />
            <br>

                必选文章标题图片<input type="file" name="head_img" />
            <br>

                <textarea id="ck-editor" name="content" class="form-control" rows="3"></textarea>
            <br>
                <button type="submit" class="btn btn-success pull-right">发贴</button>
            </form>
            </div>
    {% endif %}
   <br>
   <br>
   </div>

{% endblock %}


{% block bottom-js %}
    <script>
         CKEDITOR.replace( 'ck-editor' );
         CKEDITOR.editorConfig = function( config ) {
{#            config.language = 'es';#}
            config.uiColor = '#F7B42C';
            config.height = 500;
            config.toolbarCanCollapse = true;
};
    </script>
{% endblock %}